In [63]:
import pandas as pd
import numpy as np

In [65]:
match=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries.csv')

In [66]:
match.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [69]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [71]:
total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [72]:
total_score_df

      match_id  inning  total_runs
0       335982       1         222
1       335982       2          82
2       335983       1         240
3       335983       2         207
4       335984       1         129
...        ...     ...         ...
2212   1426310       2         174
2213   1426311       1         175
2214   1426311       2         139
2215   1426312       1         113
2216   1426312       2         114

[2217 rows x 3 columns]

In [75]:
total_score_df=total_score_df[total_score_df['inning']==1]

In [77]:
total_score_df.head()

   match_id  inning  total_runs
0    335982       1         222
2    335983       1         240
4    335984       1         129
6    335985       1         165
8    335986       1         110

In [79]:
match_df=match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')

In [81]:
match_df.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,222
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,240
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,129
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,165
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,110
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,...,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin,335987,166
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,...,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba,335988,142
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,...,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar,335989,208
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,...,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson,335990,214
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,...,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba,335991,182

In [83]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [85]:
teams=['Royal Challengers Bangalore', 'Kings XI Punjab',
        'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals',  'Chennai Super Kings',
       'Pune Warriors', 'Sunrisers Hyderabad',
        'Delhi Capitals']

In [87]:
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [89]:
match_df=match_df[match_df['team1'].isin(teams)]
match_df=match_df[match_df['team2'].isin(teams)]

In [91]:
 match_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 884 entries, 0 to 1094
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               884 non-null    int64
 1   season           884 non-null    object
 2   city             833 non-null    object
 3   date             884 non-null    object
 4   match_type       884 non-null    object
 5   player_of_match  880 non-null    object
 6   venue            884 non-null    object
 7   team1            884 non-null    object
 8   team2            884 non-null    object
 9   toss_winner      884 non-null    object
 10  toss_decision    884 non-null    object
 11  winner           880 non-null    object
 12  result           884 non-null    object
 13  result_margin    867 non-null    float64
 14  target_runs      882 non-null    float64
 15  target_overs     882 non-null    float64
 16  super_over       884 non-null    object
 17  method           15 non-null     object
 18  umpire1          884 non-null    object
 19  umpire2          884 non-null    object
 20  match_id         884 non-null    int64
 21  total_runs       884 non-null    int64
dtypes: float64(3), int64(3), object(16)
memory usage: 158.8+ KB

In [93]:
match_df=match_df[['match_id','winner','total_runs']]

In [95]:
delivery_df=match_df.merge(delivery,on='match_id')
delivery_df

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210527,1426312,Kolkata Knight Riders,113,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
210528,1426312,Kolkata Knight Riders,113,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
210529,1426312,Kolkata Knight Riders,113,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
210530,1426312,Kolkata Knight Riders,113,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
210531,1426312,Kolkata Knight Riders,113,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [97]:
delivery_df=delivery_df[delivery_df['inning']==1]

In [99]:
delivery_df.head(10)

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

In [101]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108816 entries, 0 to 210464
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          108816 non-null  int64
 1   winner            108471 non-null  object
 2   total_runs_x      108816 non-null  int64
 3   inning            108816 non-null  int64
 4   batting_team      108816 non-null  object
 5   bowling_team      108816 non-null  object
 6   over              108816 non-null  int64
 7   ball              108816 non-null  int64
 8   batter            108816 non-null  object
 9   bowler            108816 non-null  object
 10  non_striker       108816 non-null  object
 11  batsman_runs      108816 non-null  int64
 12  extra_runs        108816 non-null  int64
 13  total_runs_y      108816 non-null  int64
 14  extras_type       5939 non-null    object
 15  is_wicket         108816 non-null  int64
 16  player_dismissed  5365 non-null    object
 17  dismissal_kind    5365 non-null    object
 18  fielder           3904 non-null    object
dtypes: int64(9), object(10)
memory usage: 16.6+ MB

In [103]:
print(delivery_df['total_runs_y'].dtype)

int64

In [105]:
delivery_df['current_score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\2360476087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['current_score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [107]:
delivery_df.head(20)

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,1
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,1
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN,2
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,2
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,2
5,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,2
6,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN,3
7,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,3
8,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN,7
9,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN,11
10,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN,17
11,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN,21
12,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,21
13,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN,21
14,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN,21
15,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,22
16,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN,26
17,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,P Kumar,SC Ganguly,1,0,1,NaN,0,NaN,NaN,NaN,27
18,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN,27
19,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,SC Ganguly,0,5,5,wides,0,NaN,NaN,NaN,32

In [109]:
delivery_df['runs_left']=delivery_df['total_runs_x']-delivery_df['current_score']

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\3239114318.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['runs_left']=delivery_df['total_runs_x']-delivery_df['current_score']

In [111]:
delivery_df

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,...,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,0,1,1,legbyes,0,NaN,NaN,NaN,1,221
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,1,221
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,0,1,1,wides,0,NaN,NaN,NaN,2,220
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,2,220
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,0,0,0,NaN,0,NaN,NaN,NaN,2,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210460,1426312,Kolkata Knight Riders,113,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,JD Unadkat,SP Narine,...,0,0,0,NaN,1,JD Unadkat,lbw,NaN,113,0
210461,1426312,Kolkata Knight Riders,113,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,B Kumar,SP Narine,...,0,0,0,NaN,0,NaN,NaN,NaN,113,0
210462,1426312,Kolkata Knight Riders,113,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,PJ Cummins,AD Russell,...,0,0,0,NaN,0,NaN,NaN,NaN,113,0
210463,1426312,Kolkata Knight Riders,113,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,PJ Cummins,AD Russell,...,0,0,0,NaN,0,NaN,NaN,NaN,113,0
210464,1426312,Kolkata Knight Riders,113,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,PJ Cummins,AD Russell,...,0,0,0,NaN,1,PJ Cummins,caught,MA Starc,113,0

In [113]:
delivery_df['over'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
delivery_df['balls_left']=120-(delivery_df['over']*6 + delivery_df['ball'])

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\1980926710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['balls_left']=120-(delivery_df['over']*6 + delivery_df['ball'])

In [117]:
delivery_df.head(20)

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,...,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,1,1,legbyes,0,NaN,NaN,NaN,1,221,119
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,1,221,118
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,1,1,wides,0,NaN,NaN,NaN,2,220,117
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,2,220,116
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,2,220,115
5,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,2,220,114
6,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,...,1,1,legbyes,0,NaN,NaN,NaN,3,219,113
7,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,...,0,0,NaN,0,NaN,NaN,NaN,3,219,113
8,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,...,0,4,NaN,0,NaN,NaN,NaN,7,215,112
9,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,...,0,4,NaN,0,NaN,NaN,NaN,11,211,111
10,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,...,0,6,NaN,0,NaN,NaN,NaN,17,205,110
11,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,...,0,4,NaN,0,NaN,NaN,NaN,21,201,109
12,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,Z Khan,...,0,0,NaN,0,NaN,NaN,NaN,21,201,108
13,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,SC Ganguly,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,21,201,107
14,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,SC Ganguly,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,21,201,106
15,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,...,1,1,legbyes,0,NaN,NaN,NaN,22,200,105
16,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,...,0,4,NaN,0,NaN,NaN,NaN,26,196,104
17,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,P Kumar,...,0,1,NaN,0,NaN,NaN,NaN,27,195,103
18,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,SC Ganguly,P Kumar,...,0,0,NaN,0,NaN,NaN,NaN,27,195,102
19,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,...,5,5,wides,0,NaN,NaN,NaN,32,190,101

In [119]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna("0")

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\2323000106.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna("0")

In [121]:
delivery_df['player_dismissed']

0                  0
1                  0
2                  0
3                  0
4                  0
             ...
210460    JD Unadkat
210461             0
210462             0
210463             0
210464    PJ Cummins
Name: player_dismissed, Length: 108816, dtype: object

In [123]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\136881925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")

In [125]:

delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
wickets=delivery_df.groupby('match_id')['player_dismissed'].cumsum().values
delivery_df['wickets']=10-wickets
delivery_df.head(20)

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\4278038332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
C:\Users\patil\AppData\Local\Temp\ipykernel_2252\4278038332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['wickets']=10-wickets

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,...,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,1,legbyes,0,0,NaN,NaN,1,221,119,10
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,0,NaN,0,0,NaN,NaN,1,221,118,10
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,1,wides,0,0,NaN,NaN,2,220,117,10
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,0,NaN,0,0,NaN,NaN,2,220,116,10
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,0,NaN,0,0,NaN,NaN,2,220,115,10
5,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,...,0,NaN,0,0,NaN,NaN,2,220,114,10
6,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,...,1,legbyes,0,0,NaN,NaN,3,219,113,10
7,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,...,0,NaN,0,0,NaN,NaN,3,219,113,10
8,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,...,4,NaN,0,0,NaN,NaN,7,215,112,10
9,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,...,4,NaN,0,0,NaN,NaN,11,211,111,10
10,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,...,6,NaN,0,0,NaN,NaN,17,205,110,10
11,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,...,4,NaN,0,0,NaN,NaN,21,201,109,10
12,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,Z Khan,...,0,NaN,0,0,NaN,NaN,21,201,108,10
13,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,SC Ganguly,P Kumar,...,0,NaN,0,0,NaN,NaN,21,201,107,10
14,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,SC Ganguly,P Kumar,...,0,NaN,0,0,NaN,NaN,21,201,106,10
15,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,...,1,legbyes,0,0,NaN,NaN,22,200,105,10
16,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,...,4,NaN,0,0,NaN,NaN,26,196,104,10
17,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,P Kumar,...,1,NaN,0,0,NaN,NaN,27,195,103,10
18,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,SC Ganguly,P Kumar,...,0,NaN,0,0,NaN,NaN,27,195,102,10
19,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,...,5,wides,0,0,NaN,NaN,32,190,101,10

In [128]:
#crr(current run rate)=runs/overs
delivery_df['crr']=(delivery_df['current_score']*6)/(120-delivery_df['balls_left'])
delivery_df.head()

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\4072022408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['crr']=(delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,...,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets,crr
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,legbyes,0,0,NaN,NaN,1,221,119,10,6.0
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,NaN,0,0,NaN,NaN,1,221,118,10,3.0
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,wides,0,0,NaN,NaN,2,220,117,10,4.0
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,NaN,0,0,NaN,NaN,2,220,116,10,3.0
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,NaN,0,0,NaN,NaN,2,220,115,10,2.4

In [130]:
#rrr(required run rate)=runs left/overs_left
delivery_df['rrr']=(delivery_df['runs_left']*6)/(delivery_df['balls_left'])

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\3237022678.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['rrr']=(delivery_df['runs_left']*6)/(delivery_df['balls_left'])

In [132]:
delivery_df.head()

,match_id,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,...,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets,crr,rrr
0,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,...,0,0,NaN,NaN,1,221,119,10,6.0,11.142857
1,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,...,0,0,NaN,NaN,1,221,118,10,3.0,11.237288
2,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,...,0,0,NaN,NaN,2,220,117,10,4.0,11.282051
3,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,...,0,0,NaN,NaN,2,220,116,10,3.0,11.379310
4,335982,Kolkata Knight Riders,222,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,...,0,0,NaN,NaN,2,220,115,10,2.4,11.478261

In [134]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [136]:
delivery_df['result']=delivery_df.apply(result,axis=1)
delivery_df['result']

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\2269197785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['result']=delivery_df.apply(result,axis=1)

0         1
1         1
2         1
3         1
4         1
         ..
210460    0
210461    0
210462    0
210463    0
210464    0
Name: result, Length: 108816, dtype: int64

In [138]:
final_df=delivery_df[['batting_team','bowling_team','runs_left','balls_left','wickets','total_runs_x','crr','rrr','result']]

In [140]:
final_df

,batting_team,bowling_team,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
0,Kolkata Knight Riders,Royal Challengers Bangalore,221,119,10,222,6.000000,11.142857,1
1,Kolkata Knight Riders,Royal Challengers Bangalore,221,118,10,222,3.000000,11.237288,1
2,Kolkata Knight Riders,Royal Challengers Bangalore,220,117,10,222,4.000000,11.282051,1
3,Kolkata Knight Riders,Royal Challengers Bangalore,220,116,10,222,3.000000,11.379310,1
4,Kolkata Knight Riders,Royal Challengers Bangalore,220,115,10,222,2.400000,11.478261,1
...,...,...,...,...,...,...,...,...,...
210460,Sunrisers Hyderabad,Kolkata Knight Riders,0,13,1,113,6.336449,0.000000,0
210461,Sunrisers Hyderabad,Kolkata Knight Riders,0,12,1,113,6.277778,0.000000,0
210462,Sunrisers Hyderabad,Kolkata Knight Riders,0,11,1,113,6.220183,0.000000,0
210463,Sunrisers Hyderabad,Kolkata Knight Riders,0,10,1,113,6.163636,0.000000,0
210464,Sunrisers Hyderabad,Kolkata Knight Riders,0,9,0,113,6.108108,0.000000,0

In [142]:
final_df.sample()

,batting_team,bowling_team,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
129163,Delhi Daredevils,Kolkata Knight Riders,57,28,6,168,7.23913,12.214286,0

In [144]:
final_df.isnull().sum()

batting_team      0
bowling_team      0
runs_left         0
balls_left        0
wickets           0
total_runs_x      0
crr               0
rrr             630
result            0
dtype: int64

In [150]:
final_df=final_df[final_df['balls_left']!=0]

In [152]:
final_df.dropna(inplace=True)

C:\Users\patil\AppData\Local\Temp\ipykernel_2252\2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [154]:
X=final_df.drop('result',axis=1)
X

,batting_team,bowling_team,runs_left,balls_left,wickets,total_runs_x,crr,rrr
0,Kolkata Knight Riders,Royal Challengers Bangalore,221,119,10,222,6.000000,11.142857
1,Kolkata Knight Riders,Royal Challengers Bangalore,221,118,10,222,3.000000,11.237288
2,Kolkata Knight Riders,Royal Challengers Bangalore,220,117,10,222,4.000000,11.282051
3,Kolkata Knight Riders,Royal Challengers Bangalore,220,116,10,222,3.000000,11.379310
4,Kolkata Knight Riders,Royal Challengers Bangalore,220,115,10,222,2.400000,11.478261
...,...,...,...,...,...,...,...,...
210460,Sunrisers Hyderabad,Kolkata Knight Riders,0,13,1,113,6.336449,0.000000
210461,Sunrisers Hyderabad,Kolkata Knight Riders,0,12,1,113,6.277778,0.000000
210462,Sunrisers Hyderabad,Kolkata Knight Riders,0,11,1,113,6.220183,0.000000
210463,Sunrisers Hyderabad,Kolkata Knight Riders,0,10,1,113,6.163636,0.000000
210464,Sunrisers Hyderabad,Kolkata Knight Riders,0,9,0,113,6.108108,0.000000

In [156]:
y=final_df['result']
y

0         1
1         1
2         1
3         1
4         1
         ..
210460    0
210461    0
210462    0
210463    0
210464    0
Name: result, Length: 107995, dtype: int64

In [158]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [159]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf=ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team'])
]
                      ,remainder='passthrough')

In [174]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [180]:
pipe=Pipeline(steps=[
    ('step1',trf),
    ##('step2',LogisticRegression(solver='liblinear')),
    ('step2',RandomForestClassifier())
])

In [182]:
pipe.fit(X_train,y_train)

C:\Users\patil\AppData\Roaming\Python\Python312\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team'])])),
                ('step2', RandomForestClassifier())])

In [184]:
X_train.describe()

,runs_left,balls_left,wickets,total_runs_x,crr,rrr
count,86396.000000,86396.000000,86396.000000,86396.000000,86396.000000,86396.000000
mean,88.461167,60.171536,7.616406,164.902542,7.354021,9.429346
std,51.172871,34.409754,2.008778,31.116214,2.268947,3.700856
min,0.000000,-4.000000,0.000000,56.000000,0.000000,-36.000000
25%,47.000000,30.000000,6.000000,145.000000,6.142857,7.534884
50%,87.000000,60.000000,8.000000,165.000000,7.410230,9.000000
75%,127.000000,90.000000,9.000000,185.000000,8.571429,10.800000
max,276.000000,119.000000,10.000000,277.000000,36.000000,132.000000

In [186]:
y_pred=pipe.predict(X_test)

In [188]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9945830825501181

In [190]:
teams

['Royal Challengers Bangalore',
 'Kings XI Punjab',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Chennai Super Kings',
 'Pune Warriors',
 'Sunrisers Hyderabad',
 'Delhi Capitals']

In [192]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))